[package]
name = "graph-server-graphman"
version.workspace = true
edition.workspace = true

[dependencies]
futures = "0.1.21"
graphql-parser = "0.4.0"
http = "0.2"
hyper = "0.14"
serde = { version = "1.0", features = ["derive"] }
juniper = "0.15.11"
graph = { path = "../../graph" }
graph-graphql = { path = "../../graphql" }
graphql-utils = { path = "../graphql_utils" }
graph-core = { path = "../../core" }
juniper_hyper = "0.8.0"
graph-store-postgres = { path = "../../store/postgres" }
